version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - my_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: backend1
    depends_on:
      - mongodb
    networks:
      - my_network
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://mongodb:27017"

volumes:
  mongodb_data:

networks:
  my_network:
